# Generated by Django 5.1.1 on 2024-10-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='profile',
            field=models.ImageField(blank=True, default='eulogy_fallback.png', upload_to=''),
        ),
    ]
